title: Trey's Engineering Portfolio
description: Radar, RF, and signal processing projects
theme: minima
markdown: kramdown

collections:
  projects:
    output: true
    permalink: /projects/:name/

[🔬 View My Projects →](/projects/)
