title: Trey's Engineering Portfolio
description: Radar, RF, and signal processing projects
theme: minima
markdown: kramdown

# Optional: Show GitHub link in footer
github_username: treylt90

# Base URL (used if your repo isn't yourusername.github.io)
# Leave blank for personal site
baseurl: ""  # important to leave empty for personal GitHub Pages site

# If you want posts (optional)
# future: true

